import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Landing Page
    'landing.welcome': 'Bienvenue sur Octodash',
    'landing.subtitle': 'Votre tour de contrôle',
    'landing.description': "L'agent IA Octomiro a les yeux partout sur vos opérations pour contrôler, compter et identifier les anomalies.",
    'landing.email': 'Email',
    'landing.password': 'Mot de passe',
    'landing.login': 'Se connecter',
    'landing.error': 'Email ou mot de passe incorrect',
    'landing.powered': 'Propulsé par l\'intelligence artificielle Octomiro',
    
    // Dashboard
    'dashboard.title': 'Dashboard Global',
    'dashboard.subtitle': 'Vue d\'ensemble de l\'activité Octomiro',
    'dashboard.productivity': 'Productivité',
    'dashboard.savings': 'Économies',
    'dashboard.compliance': 'Conformité',
    'dashboard.time': 'Temps gagné',
    'dashboard.activityByModule': 'Activité par Module',
    'dashboard.activeClients': 'Clients Actifs',
    'dashboard.active': 'Actif',
    'dashboard.inactive': 'Inactif',
    'dashboard.operations': 'opérations ce mois',
    'dashboard.kpi.productivity': 'Augmentation moyenne de la productivité grâce à l\'automatisation IA',
    'dashboard.kpi.savings': 'Économies totales réalisées pour l\'ensemble des clients',
    'dashboard.kpi.compliance': 'Taux de conformité aux normes ERP',
    'dashboard.kpi.time': 'Temps total économisé en heures de travail',
    'dashboard.kpi.vigilance': 'Indice vigilance IA',
    'dashboard.kpi.vigilance.desc': 'Score global (0-100) qui combine disponibilité du système, précision du comptage et rapidité de détection',
    'dashboard.kpi.gap': 'Écart moyen ERP vs Réalité',
    'dashboard.kpi.gap.desc': 'Mesure l\'écart entre la quantité détectée par Octomiro et la quantité attendue dans l\'ERP',
    'dashboard.kpi.deliveryCompliance': 'Taux conformité livraisons',
    'dashboard.kpi.deliveryCompliance.desc': '% des camions conformes (nombre réel = nombre ERP)',
    'dashboard.kpi.reactivity': 'Réactivité IA',
    'dashboard.kpi.reactivity.desc': 'Temps moyen entre la capture (photo ou vidéo) et la validation par Octomiro',
    'dashboard.kpi.anomalies': 'Anomalies critiques détectées',
    'dashboard.kpi.anomalies.desc': 'Nombre de cas où l\'IA a évité une erreur majeure (livraison manquante, surstock, etc.)',
    'dashboard.kpi.serenity': 'Indice sérénité client',
    'dashboard.kpi.serenity.desc': '% de livraisons validées automatiquement sans intervention humaine',
    'dashboard.demo': 'Démo',
    
    // Clients
    'clients.title': 'Gestion des Clients',
    'clients.subtitle': 'Gestion et suivi des clients Octomiro',
    'clients.search': 'Rechercher un client...',
    'clients.activeModules': 'Modules actifs',
    'clients.operations': 'Opérations',
    'clients.thisMonth': 'ce mois',
    'clients.newClient': 'Nouveau Client',
    'clients.ameurPlastics.name': 'Ameur Plastics',
    'clients.ameurPlastics.desc': 'Fabricant de produits plastiques industriels',
    'clients.ameurPlastics.erp': 'ERP Octal - Comparaison avec Bon de livraison',
    'clients.tunifries.name': 'TuniFries',
    'clients.tunifries.desc': 'Production agroalimentaire',
    'clients.tunifries.erp': 'ERP Navision - Comparaison avec Bon de chargement',
    'clients.padelConnection.name': 'Padel Connection',
    'clients.padelConnection.desc': 'Gestion de terrains de padel',
    'clients.octomiro.name': 'Octomiro (Interne)',
    'clients.octomiro.desc': 'Environnement de test et développement',
    
    // Client Detail
    'clientDetail.overview': 'Vue d\'ensemble',
    'clientDetail.statistics': 'Statistiques',
    'clientDetail.recentActivity': 'Activité récente',
    'clientDetail.activeModules': 'Modules actifs',
    'clientDetail.totalOperations': 'Opérations totales',
    'clientDetail.avgAccuracy': 'Précision moyenne',
    'clientDetail.timeSaved': 'Temps économisé',
    'clientDetail.productivity': 'Productivité',
    'clientDetail.compliance': 'Conformité',
    'clientDetail.errorRate': 'Taux d\'erreur',
    'clientDetail.hours': 'heures',
    'clientDetail.backToClients': 'Retour aux clients',
    'clientDetail.ameurPlastics.desc': 'Fabricant de produits plastiques industriels - Chargement de camions',
    'clientDetail.tunifries.desc': 'Production agroalimentaire - Chargement de camions frigorifiques',
    'clientDetail.padelConnection.desc': 'Gestion de terrains de padel',
    'clientDetail.octomiro.desc': 'Environnement de test et développement',
    'clientDetail.monthlyStats': 'Statistiques du mois',
    'clientDetail.recentDeliveries': 'Dernières livraisons',
    'clientDetail.recentLoadings': 'Derniers chargements',
    'clientDetail.watchVideo': 'Voir la vidéo',
    'clientDetail.videoNotSupported': 'Votre navigateur ne supporte pas la balise vidéo.',
    'clientDetail.totalTrucks': 'Camions totaux',
    'clientDetail.conformTrucks': 'Camions conformes',
    'clientDetail.avgTrucksPerDay': 'Moyenne camions/jour',
    'clientDetail.avgProcessingTime': 'Temps de traitement moyen',
    'clientDetail.totalTimeSaved': 'Temps total gagné',
    'clientDetail.loadingDocks': 'Quais de chargement',
    'clientDetail.criticalAnomalies': 'Anomalies critiques',
    'clientDetail.truck': 'Camion',
    'clientDetail.dock': 'Quai',
    'clientDetail.erpValue': 'Valeur ERP',
    'clientDetail.erpDocument.deliveryNote': 'Bon de livraison',
    'clientDetail.erpDocument.loadingSheet': 'Bon de chargement',
    'clientDetail.deployment.onPremise': 'On-Premise',
    'clientDetail.deployment.cloudSaas': 'Cloud SaaS',
    'clientDetail.aiDetected': 'Détecté par IA',
    'clientDetail.processingTime': 'Temps de calcul',
    'clientDetail.conform': 'conforme',
    'clientDetail.minorGap': 'écart mineur',
    'clientDetail.anomalyDetected': 'anomalie détectée',
    'clientDetail.activity': 'Activité',
    'clientDetail.dashboards': 'Dashboards',
    'clientDetail.history': 'Historique',
    'clientDetail.open': 'Ouvrir',
    'clientDetail.historyPlaceholder': 'Historique complet des opérations à venir...',
    'clientDetail.tests': 'tests',
    'clientDetail.accuracy': 'accuracy',
    'clientDetail.models': 'models',
    'clientDetail.datasets': 'datasets',
    
    // Applications
    'applications.title': 'Applications Octomiro',
    'applications.subtitle': 'Vue d\'ensemble des modules Octomiro et leurs performances',
    'applications.learnMore': 'En savoir plus',
    'applications.octoxact.name': 'OctoXact',
    'applications.octoxact.desc': 'Comptage et identification en temps réel avec réconciliation ERP',
    'applications.octonorm.name': 'OctoNorm',
    'applications.octonorm.desc': 'Détection automatique d\'anomalies pour le contrôle qualité',
    'applications.octovolume.name': 'OctoVolume',
    'applications.octovolume.desc': 'Calcul de volume et optimisation logistique',
    'applications.octowatch.name': 'OctoWatch',
    'applications.octowatch.desc': 'Suivi des opérations humaines et efficacité des processus',
    'applications.precision': 'Précision',
    'applications.operations': 'Opérations',
    'applications.clients': 'Clients',
    'applications.controls': 'Contrôles',
    'applications.anomalies': 'Anomalies',
    'applications.detectionRate': 'Taux détection',
    'applications.calculations': 'Calculs',
    'applications.timeGain': 'Gain temps',
    'applications.surveillance': 'Surveillances',
    'applications.efficiency': 'Efficacité',
    'applications.alerts': 'Alertes',
    
    // Testing Platform
    'testing.title': 'Testing Platform',
    'testing.subtitle': 'Testez vos images/vidéos et comparez avec l\'ERP simulé',
    'testing.uploadConfig': 'Upload & Configuration',
    'testing.imageOrVideo': 'Image ou Vidéo',
    'testing.clickToUpload': 'Cliquez pour uploader',
    'testing.realCount': 'Compte Réel (ERP)',
    'testing.example': 'Ex: 173',
    'testing.launchTest': 'Lancer le Test',
    'testing.results': 'Résultats',
    'testing.conform': 'Conforme',
    'testing.notConform': 'Non Conforme',
    'testing.aiMatchesErp': 'Le comptage IA correspond à l\'ERP',
    'testing.gapDetected': 'Écart détecté avec l\'ERP',
    'testing.aiCount': 'Comptage IA',
    'testing.erpCount': 'Compte ERP',
    'testing.precision': 'Précision',
    'testing.time': 'Temps',
    'testing.waitingForTest': 'En attente de test...',
    'testing.error': 'Erreur',
    'testing.errorMessage': 'Veuillez uploader une image/vidéo et saisir le compte ERP',
    
    // Administration
    'admin.title': 'Administration',
    'admin.subtitle': 'Gestion des clients, utilisateurs et paramètres',
    'admin.addClient': 'Ajouter un Client',
    'admin.addClientDesc': 'Créer un nouveau compte client et configurer ses applications',
    'admin.newClient': 'Nouveau Client',
    'admin.userManagement': 'Gestion Utilisateurs',
    'admin.userManagementDesc': 'Gérer les accès et permissions des utilisateurs',
    'admin.manage': 'Gérer',
    'admin.systemSettings': 'Paramètres Système',
    'admin.systemSettingsDesc': 'Configuration globale de l\'application',
    'admin.configure': 'Configurer',
    'admin.database': 'Base de Données',
    'admin.databaseDesc': 'Statistiques et maintenance de la base de données',
    'admin.viewStats': 'Voir Stats',
    'admin.globalStats': 'Statistiques Globales',
    'admin.activeClients': 'Clients Actifs',
    'admin.applications': 'Applications',
    'admin.totalOperations': 'Opérations Totales',
    'admin.uptime': 'Uptime',
    
    // Not Found
    'notFound.title': '404',
    'notFound.message': 'Oups! Page non trouvée',
    'notFound.returnHome': 'Retour à l\'accueil',
    
    // Sidebar
    'sidebar.dashboard': 'Dashboard Global',
    'sidebar.clients': 'Clients',
    'sidebar.applications': 'Applications',
    'sidebar.testing': 'Testing Platform',
    'sidebar.admin': 'Administration',
    'sidebar.tutorial': 'Tutoriel',
    'sidebar.copyright': 'Octomiro © 2025',
  },
  en: {
    // Landing Page
    'landing.welcome': 'Welcome to Octodash',
    'landing.subtitle': 'Your control tower',
    'landing.description': 'The Octomiro AI agent has eyes everywhere on your operations to control, count, and identify anomalies.',
    'landing.email': 'Email',
    'landing.password': 'Password',
    'landing.login': 'Log in',
    'landing.error': 'Incorrect email or password',
    'landing.powered': 'Powered by Octomiro artificial intelligence',
    
    // Dashboard
    'dashboard.title': 'Global Dashboard',
    'dashboard.subtitle': 'Overview of Octomiro activity',
    'dashboard.productivity': 'Productivity',
    'dashboard.savings': 'Savings',
    'dashboard.compliance': 'Compliance',
    'dashboard.time': 'Time saved',
    'dashboard.activityByModule': 'Activity by Module',
    'dashboard.activeClients': 'Active Clients',
    'dashboard.active': 'Active',
    'dashboard.inactive': 'Inactive',
    'dashboard.operations': 'operations this month',
    'dashboard.kpi.productivity': 'Average productivity increase through AI automation',
    'dashboard.kpi.savings': 'Total savings achieved for all clients',
    'dashboard.kpi.compliance': 'ERP compliance rate',
    'dashboard.kpi.time': 'Total time saved in working hours',
    'dashboard.kpi.vigilance': 'AI Vigilance Index',
    'dashboard.kpi.vigilance.desc': 'Global score (0-100) combining system availability, counting accuracy, and detection speed',
    'dashboard.kpi.gap': 'Average ERP vs Reality Gap',
    'dashboard.kpi.gap.desc': 'Measures the gap between the quantity detected by Octomiro and the expected quantity in the ERP',
    'dashboard.kpi.deliveryCompliance': 'Delivery Compliance Rate',
    'dashboard.kpi.deliveryCompliance.desc': '% of compliant trucks (actual number = ERP number)',
    'dashboard.kpi.reactivity': 'AI Reactivity',
    'dashboard.kpi.reactivity.desc': 'Average time between capture (photo or video) and Octomiro validation',
    'dashboard.kpi.anomalies': 'Critical Anomalies Detected',
    'dashboard.kpi.anomalies.desc': 'Number of cases where AI prevented a major error (missing delivery, overstock, etc.)',
    'dashboard.kpi.serenity': 'Client Serenity Index',
    'dashboard.kpi.serenity.desc': '% of deliveries automatically validated without human intervention',
    'dashboard.demo': 'Demo',
    
    // Clients
    'clients.title': 'Client Management',
    'clients.subtitle': 'Management and monitoring of Octomiro clients',
    'clients.search': 'Search for a client...',
    'clients.activeModules': 'Active modules',
    'clients.operations': 'Operations',
    'clients.thisMonth': 'this month',
    'clients.newClient': 'New Client',
    'clients.ameurPlastics.name': 'Ameur Plastics',
    'clients.ameurPlastics.desc': 'Industrial plastic products manufacturer',
    'clients.ameurPlastics.erp': 'Octal ERP - Delivery note comparison',
    'clients.tunifries.name': 'TuniFries',
    'clients.tunifries.desc': 'Food production',
    'clients.tunifries.erp': 'Navision ERP - Loading sheet comparison',
    'clients.padelConnection.name': 'Padel Connection',
    'clients.padelConnection.desc': 'Padel court management',
    'clients.octomiro.name': 'Octomiro (Internal)',
    'clients.octomiro.desc': 'Testing and development environment',
    
    // Client Detail
    'clientDetail.overview': 'Overview',
    'clientDetail.statistics': 'Statistics',
    'clientDetail.recentActivity': 'Recent Activity',
    'clientDetail.activeModules': 'Active modules',
    'clientDetail.totalOperations': 'Total operations',
    'clientDetail.avgAccuracy': 'Average accuracy',
    'clientDetail.timeSaved': 'Time saved',
    'clientDetail.productivity': 'Productivity',
    'clientDetail.compliance': 'Compliance',
    'clientDetail.errorRate': 'Error rate',
    'clientDetail.hours': 'hours',
    'clientDetail.backToClients': 'Back to clients',
    'clientDetail.ameurPlastics.desc': 'Industrial plastic products manufacturer - Truck loading',
    'clientDetail.tunifries.desc': 'Food production - Refrigerated truck loading',
    'clientDetail.padelConnection.desc': 'Padel court management',
    'clientDetail.octomiro.desc': 'Testing and development environment',
    'clientDetail.monthlyStats': 'Monthly Statistics',
    'clientDetail.recentDeliveries': 'Recent Deliveries',
    'clientDetail.recentLoadings': 'Recent Loadings',
    'clientDetail.watchVideo': 'Watch Video',
    'clientDetail.videoNotSupported': 'Your browser does not support the video tag.',
    'clientDetail.totalTrucks': 'Total Trucks',
    'clientDetail.conformTrucks': 'Compliant Trucks',
    'clientDetail.avgTrucksPerDay': 'Average Trucks/Day',
    'clientDetail.avgProcessingTime': 'Average Processing Time',
    'clientDetail.totalTimeSaved': 'Total Time Saved',
    'clientDetail.loadingDocks': 'Loading Docks',
    'clientDetail.criticalAnomalies': 'Critical Anomalies',
    'clientDetail.truck': 'Truck',
    'clientDetail.dock': 'Dock',
    'clientDetail.erpValue': 'ERP Value',
    'clientDetail.erpDocument.deliveryNote': 'Delivery note',
    'clientDetail.erpDocument.loadingSheet': 'Loading sheet',
    'clientDetail.deployment.onPremise': 'On-Premise',
    'clientDetail.deployment.cloudSaas': 'Cloud SaaS',
    'clientDetail.aiDetected': 'Detected by AI',
    'clientDetail.processingTime': 'Processing Time',
    'clientDetail.conform': 'conform',
    'clientDetail.minorGap': 'minor gap',
    'clientDetail.anomalyDetected': 'anomaly detected',
    'clientDetail.activity': 'Activity',
    'clientDetail.dashboards': 'Dashboards',
    'clientDetail.history': 'History',
    'clientDetail.open': 'Open',
    'clientDetail.historyPlaceholder': 'Complete operation history coming soon...',
    'clientDetail.tests': 'tests',
    'clientDetail.accuracy': 'accuracy',
    'clientDetail.models': 'models',
    'clientDetail.datasets': 'datasets',
    
    // Applications
    'applications.title': 'Octomiro Applications',
    'applications.subtitle': 'Overview of Octomiro modules and their performance',
    'applications.learnMore': 'Learn more',
    'applications.octoxact.name': 'OctoXact',
    'applications.octoxact.desc': 'Real-time counting and identification with ERP reconciliation',
    'applications.octonorm.name': 'OctoNorm',
    'applications.octonorm.desc': 'Automatic anomaly detection for quality control',
    'applications.octovolume.name': 'OctoVolume',
    'applications.octovolume.desc': 'Volume calculation and logistics optimization',
    'applications.octowatch.name': 'OctoWatch',
    'applications.octowatch.desc': 'Monitoring of human operations and process efficiency',
    'applications.precision': 'Precision',
    'applications.operations': 'Operations',
    'applications.clients': 'Clients',
    'applications.controls': 'Controls',
    'applications.anomalies': 'Anomalies',
    'applications.detectionRate': 'Detection Rate',
    'applications.calculations': 'Calculations',
    'applications.timeGain': 'Time Gain',
    'applications.surveillance': 'Surveillance',
    'applications.efficiency': 'Efficiency',
    'applications.alerts': 'Alerts',
    
    // Testing Platform
    'testing.title': 'Testing Platform',
    'testing.subtitle': 'Test your images/videos and compare with simulated ERP',
    'testing.uploadConfig': 'Upload & Configuration',
    'testing.imageOrVideo': 'Image or Video',
    'testing.clickToUpload': 'Click to upload',
    'testing.realCount': 'Real Count (ERP)',
    'testing.example': 'Ex: 173',
    'testing.launchTest': 'Launch Test',
    'testing.results': 'Results',
    'testing.conform': 'Conform',
    'testing.notConform': 'Not Conform',
    'testing.aiMatchesErp': 'AI counting matches ERP',
    'testing.gapDetected': 'Gap detected with ERP',
    'testing.aiCount': 'AI Count',
    'testing.erpCount': 'ERP Count',
    'testing.precision': 'Precision',
    'testing.time': 'Time',
    'testing.waitingForTest': 'Waiting for test...',
    'testing.error': 'Error',
    'testing.errorMessage': 'Please upload an image/video and enter the ERP count',
    
    // Administration
    'admin.title': 'Administration',
    'admin.subtitle': 'Client, user, and settings management',
    'admin.addClient': 'Add Client',
    'admin.addClientDesc': 'Create a new client account and configure their applications',
    'admin.newClient': 'New Client',
    'admin.userManagement': 'User Management',
    'admin.userManagementDesc': 'Manage user access and permissions',
    'admin.manage': 'Manage',
    'admin.systemSettings': 'System Settings',
    'admin.systemSettingsDesc': 'Global application configuration',
    'admin.configure': 'Configure',
    'admin.database': 'Database',
    'admin.databaseDesc': 'Database statistics and maintenance',
    'admin.viewStats': 'View Stats',
    'admin.globalStats': 'Global Statistics',
    'admin.activeClients': 'Active Clients',
    'admin.applications': 'Applications',
    'admin.totalOperations': 'Total Operations',
    'admin.uptime': 'Uptime',
    
    // Not Found
    'notFound.title': '404',
    'notFound.message': 'Oops! Page not found',
    'notFound.returnHome': 'Return to Home',
    
    // Sidebar
    'sidebar.dashboard': 'Global Dashboard',
    'sidebar.clients': 'Clients',
    'sidebar.applications': 'Applications',
    'sidebar.testing': 'Testing Platform',
    'sidebar.admin': 'Administration',
    'sidebar.tutorial': 'Tutorial',
    'sidebar.copyright': 'Octomiro © 2025',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
